config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, :start, :finish, presence: true
    validate :finish, if: :finish_date
    
end

def finish_date
    return if finish.blank? || start.blank?
    if finish >= start
    else
        errors.add(:finish, "は開始日より前の日付で登録できません。")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedule = Schedule.all
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :finish, :check, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :schedules
    else
      render "new"
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start, :finish, :check, :memo))
      flash[:notice] = "IDが「#{@schedule.id}」のスケジュールを更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer>
      <h1>現在の日時 : <%= Date.today.strftime("%Y年%m月%d日") %>  スケジュール合計 : <%= Schedule.all.count(:id) %></h1>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
  
    <tr>
      <th><%= f.label :start ,"開始日" %></th>
      <td><%= f.date_field :start %></td>
    </tr>

    <tr>
      <th><%= f.label :finish ,"終了日" %></th>
      <td><%= f.date_field :finish %></td>
    </tr>

    <tr>
      <th><%= f.label :check ,"終日" %></th>
      <td><%= f.check_box :check %><%= "終日の場合はチェックを入れます" %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>
  <div>
    <ul>
      <li><%= f.submit "スケジュールの編集を完了する" %></li>
      <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h3>スケジュール一覧</h3>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>スケジュール更新日時</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    
    <tbody>
        <% @schedule.each do |schedule| %>
            <tr>
                <td><%= schedule.id %></td>
                <td><%= schedule.title %></td>
                <td><%= schedule.start.strftime("%Y年%m月%d日") %></td>
                <td><%= schedule.finish.strftime("%Y年%m月%d日") %></td>
                <td><% if schedule.check == true %>
                    ○
                    <% else %>
                    
                    <% end %></td>
                <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
                <td>
                    <%= link_to "確認", schedule %>
                </td>
                <td>
                    <%= link_to "編集", [:edit, schedule] %>
                </td>
                <td>
                    <%= link_to "削除", schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "ユーザー新規登録", :new_schedule %></p>

app/views/schedules/new.html.erb
<h3>スケジュール新規作成</h3>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
  
    <tr>
      <th><%= f.label :start ,"開始日" %></th>
      <td><%= f.date_field :start %></td>
    </tr>

    <tr>
      <th><%= f.label :finish ,"終了日" %></th>
      <td><%= f.date_field :finish %></td>
    </tr>

    <tr>
      <th><%= f.label :check ,"終日" %></th>
      <td><%= f.check_box :check %><%= "終日の場合はチェックを入れます" %></td>
    </tr>

    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "スケジュールを新規登録する" %></li>
      <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h3>スケジュール詳細</h3>
 
<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.finish.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><% if @schedule.check == true %>
        ○
        <% else %>
        
        <% end %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    <li><%= link_to "スケジュールを編集する", :edit_schedule %></li>
    <li><%= link_to "スケジュールを削除する", schedule_path(@schedule.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
  </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>